/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ba8a00",
        "secondary-fixed": "#ffdcc3",
        "on-primary-fixed-variant": "#374765",
        "surface-container-low": "#f2f4f7",
        "outline-variant": "#c5c6ce",
        "tertiary-fixed": "#ffdfa0",
        "primary-fixed-dim": "#b6c7eb",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef1",
        "surface-dim": "#d8dadd",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#261a00",
        error: "#ba1a1a",
        "inverse-surface": "#2d3133",
        "on-surface-variant": "#44474d",
        "on-secondary-container": "#603100",
        background: "#f7f9fc",
        "tertiary-fixed-dim": "#f8bd2a",
        "on-error-container": "#93000a",
        "on-surface": "#191c1e",
        "primary-container": "#1a2b48",
        secondary: "#904d00",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#081b38",
        tertiary: "#1f1500",
        "on-secondary-fixed": "#2f1500",
        "surface-tint": "#4e5f7e",
        "error-container": "#ffdad6",
        outline: "#75777e",
        "on-primary": "#ffffff",
        "secondary-container": "#fd8b00",
        surface: "#f7f9fc",
        "surface-container-highest": "#e0e3e6",
        "on-primary-container": "#8293b5",
        "surface-bright": "#f7f9fc",
        "inverse-on-surface": "#eff1f4",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#5c4300",
        "secondary-fixed-dim": "#ffb77d",
        primary: "#031632",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e6",
        "inverse-primary": "#b6c7eb",
        "tertiary-container": "#392800",
        "primary-fixed": "#d7e2ff",
        "on-secondary-fixed-variant": "#6e3900",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
